version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    target-branch: "dev"
    schedule:
      interval: weekly
    groups:
      actions:
        patterns:
          - "*"

  - package-ecosystem: pip
    versioning-strategy: lockfile-only
    directory: /
    target-branch: "dev"
    schedule:
      interval: weekly
    groups:
      actions:
        patterns:
          - "*"
