version: 2
updates:
    - package-ecosystem: github-actions
      directory: /
      schedule:
          interval: monthly
    - package-ecosystem: pip
      directory: /
      schedule:
          interval: monthly
      insecure-external-code-execution: allow
