version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    target-branch: "master"
    schedule:
      interval: weekly
    labels:
      - "is: chore"
      - "topic: github actions"
    groups:
      actions:
        patterns:
          - "*"
  - package-ecosystem: uv
    directory: /
    target-branch: master
    schedule:
      interval: weekly
    labels:
      - "is: chore"
      - "topic: dependencies"
    groups:
      actions:
        patterns:
          - "*"
