changelog:
  categories:
    - title: "`optype`"
      labels:
        - "component: optype"
    - title: "`optype.numpy`"
      labels:
        - "component: optype.numpy"
    - title: "`optype.copy`"
      labels:
        - "component: optype.copy"
    - title: "`optype.dataclasses`"
      labels:
        - "component: optype.dataclasses"
    - title: "`optype.dlpack`"
      labels:
        - "component: optype.dlpack"
    - title: "`optype.inspect`"
      labels:
        - "component: optype.inspect"
    - title: "`optype.pickle`"
      labels:
        - "component: optype.pickle"
    - title: "`optype.string`"
      labels:
        - "component: optype.string"
    - title: "`optype.types`"
      labels:
        - "component: optype.types"
    - title: "`optype.typing`"
      labels:
        - "component: optype.typing"
    - title: Documentation
      labels:
        - "04 - Documentation"
    - title: Dependencies
      labels:
        - "component: Dependencies"
    - title: Continuous integration
      labels:
        - "component: Github actions"
    - title: Other Changes
      labels:
        - "*"
