changelog:
  categories:
    - title: "`optype`"
      labels:
        - "optype.Can*"
        - "optype.Has*"
        - "optype.Does*"
        - "optype.Just*"
        - "optype.do_*"
    - title: "`optype.numpy`"
      labels:
        - "optype.numpy"
    - title: "`optype.copy`"
      labels:
        - "optype.copy"
    - title: "`optype.dataclasses`"
      labels:
        - "optype.dataclasses"
    - title: "`optype.dlpack`"
      labels:
        - "optype.dlpack"
    - title: "`optype.inspect`"
      labels:
        - "optype.inspect"
    - title: "`optype.pickle`"
      labels:
        - "optype.pickle"
    - title: "`optype.string`"
      labels:
        - "optype.string"
    - title: "`optype.types`"
      labels:
        - "optype.types"
    - title: "`optype.typing`"
      labels:
        - "optype.typing"
    - title: Documentation
      labels:
        - "topic: documentation"
    - title: Dependencies
      labels:
        - "topic: dependencies"
    - title: Testing
      labels:
        - "topic: testing"
    - title: Continuous integration
      labels:
        - "topic: github actions"
    - title: Other Changes
      labels:
        - "*"
