default: true
no-hard-tabs: true

MD007:
  indent: 4
MD013:
  line_length: 79
MD031:
  list_items: false
MD033:
  allowed_elements:
    - h1
    - p
    - br
    - a
    - i
    - code
    - img
    - table
    - tr
    - th
    - td
