default: true
no-hard-tabs: true

MD007:
  indent: 4
MD013:
  line_length: 88
MD031:
  list_items: false
MD033:
  allowed_elements:
    - h1
    - p
    - br
    - a
    - i
    - code
    - sup
    - sub
    - img
    - table
    - tr
    - th
    - td
    - dl
    - dt
    - dd
    - details
    - summary
