ci:
  autoupdate_branch: "master"
  autoupdate_commit_msg: "update pre-commit hooks"
  skip:
    - markdownlint
    - codespell
    - ruff
    - ruff-format
    - basedmypy
    - basedpyright
    - basedpyright-verifytypes

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-illegal-windows-names
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: destroyed-symlinks
      - id: detect-aws-credentials
        args: [--allow-missing-credentials]
      - id: detect-private-key
      - id: fix-byte-order-marker
      - id: forbid-submodules
      - id: no-commit-to-branch
        args: [--branch, master]
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]

  - repo: https://github.com/adamchainz/blacken-docs
    rev: "1.19.1"
    hooks:
      - id: blacken-docs
        additional_dependencies:
          - black==24.10.0

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.42.0
    hooks:
      - id: markdownlint

  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        additional_dependencies:
          - tomli

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.2
    hooks:
      - id: ruff
        args: [--fix, --show-fixes]
      - id: ruff-format

  - repo: local
    hooks:
      - id: basedmypy
        name: basedmypy
        entry: uv run mypy
        language: system
        types_or: [python, pyi]

      - id: basedpyright
        name: basedpyright
        entry: uv run basedpyright
        language: system
        types_or: [python, pyi]

      - id: basedpyright-verifytypes
        name: basedpyright --verifytypes
        entry: uv run basedpyright --ignoreexternal --verifytypes optype
        language: system
        always_run: true
        pass_filenames: false
