ci:
  autoupdate_branch: "dev"
  autoupdate_commit_msg: "update pre-commit hooks"
  skip:
    - markdownlint
    - poetry-check
    - poetry-lock
    - codespell
    - ruff
    - basedpyright

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: destroyed-symlinks
      - id: detect-aws-credentials
        args: [--allow-missing-credentials]
      - id: detect-private-key
      - id: fix-byte-order-marker
      - id: forbid-submodules
      - id: no-commit-to-branch
        args: [--branch, master, --branch, dev]
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.41.0
    hooks:
      - id: markdownlint

  - repo: https://github.com/python-poetry/poetry
    rev: 1.8.3
    hooks:
      - id: poetry-check
      - id: poetry-lock
        args: [--no-update]

  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        additional_dependencies:
          - tomli

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.5
    hooks:
      - id: ruff
        args: [--fix, --show-fixes]

  - repo: local
    hooks:
      - id: basedpyright
        name: basedpyright
        entry: poetry run basedpyright
        language: system
        always_run: true
        pass_filenames: false
