extend = "../../pyproject.toml"
cache-dir = "../../.ruff_cache"

[lint.per-file-ignores]
"_api.py" = ["PLR0402"]
"_cli.py" = ["S102", "S307", "T201"]
"_explore.py" = ["PLR0914"]
"_numpy.py" = ["PLR0402"]
"_protocols.py" = ["PLR0402"]
"_render.py" = ["PLR0402"]
"_spy.py" = ["TD002", "TD003", "PYI034", "PYI047", "PLR0904"]

[lint.pylint]
allow-dunder-method-names = [
  "__array_function__",
  "__array_ufunc__",
  "__optype_trace_add__",
]
