extend = "../../pyproject.toml"
cache-dir = "../../.ruff_cache"

[lint.per-file-ignores]
"_api.py" = ["manual-from-import"]
"_cli.py" = ["exec-builtin", "suspicious-eval-usage", "print"]
"_explore.py" = ["too-many-locals"]
"_numpy.py" = ["manual-from-import"]
"_protocols.py" = ["manual-from-import"]
"_render.py" = ["manual-from-import"]
"_spy.py" = [
  "missing-todo-author",
  "missing-todo-link",
  "non-self-return-type",
  "too-many-public-methods",
]

[lint.pylint]
allow-dunder-method-names = [
  "__array_function__",
  "__array_ufunc__",
  "__optype_trace_add__",
]
