name: CI
permissions: {}

on:
  pull_request:
  push:
    branches: [master]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  UV_LOCKED: 1
  NPTC_BUILD: 20260602

jobs:
  lint:
    name: lint
    timeout-minutes: 5
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: typos
        uses: crate-ci/typos@bee27e3a4fd1ea2111cf90ab89cd076c870fce14 # v1.48.0

      - uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
        with:
          python-version: "3.14"

      - name: dprint
        run: uv run dprint check

      # the `scientific-python/repo-review` action (v1.0.3) internally uses an unpinned
      # `actions/setup-python@v6`, so we use `uvx` instead.
      - name: repo-review
        run: >
          uvx --from='repo-review[cli]' --with=sp-repo-review
          repo-review --format html --stderr rich .
          >> $GITHUB_STEP_SUMMARY

      - name: ruff check
        run: uv run ruff check --output-format=github

      - name: ruff format
        run: uv run ruff format --check

      - name: basedpyright --verifytypes
        run: uv run basedpyright --ignoreexternal --verifytypes optype

  typecheck:
    name: typecheck
    timeout-minutes: 5
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        py: ["3.12", "3.14"]
        np: ["2.0", "2.1", "2.2", "2.3", "2.4", "2.5"]
        exclude:
          - py: "3.13"
            np: "2.0"
          - py: "3.14"
            np: "2.0"
          - py: "3.14"
            np: "2.1"
        include:
          - py: "3.15"
            np: "2.5"
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
        with:
          activate-environment: true
          python-version: ${{ matrix.py }}

      - name: uv sync
        run: uv sync --no-editable

      - name: install deps
        run: uv pip install --exact --group type "numpy==$NP_VERSION.*" .
        env:
          NP_VERSION: ${{ matrix.np }}

      - name: ty
        run: ty check

      - name: pyrefly
        run: pyrefly check

      - name: basedpyright
        run: basedpyright

      # NOTE: mypy ignores `uv run --with=...` (and `--isolated` does not help)
      - name: mypy
        run: mypy --no-incremental --cache-dir=/dev/null .

  test:
    name: test
    timeout-minutes: 10
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, windows]
        py: ["3.12", "3.13", "3.14"]
        np: ["2.0", "2.4", "2.5"]
        exclude:
          - py: "3.13"
            np: "2.0"
          - py: "3.14"
            np: "2.0"
        include:
          - os: ubuntu
            py: "3.15"
            np: "2.5"
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
        with:
          python-version: ${{ matrix.py }}
          activate-environment: true

      - name: install dependencies
        shell: bash
        run: uv pip install --exact --group test "numpy==$NP_VERSION.*" .
        env:
          NP_VERSION: ${{ matrix.np }}

      - name: pytest
        run: pytest
