name: deploy docs

on:
  push:
    branches: [master]
    paths:
      - "docs/**"
      - ".github/workflows/docs.yml"
      - "zensical.toml"
      - "uv.lock"
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      pages: write # deploy to GitHub Pages
      id-token: write # authenticate with GitHub Pages OIDC

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - uses: actions/configure-pages@45bfe0192ca1faeb007ade9deae92b16b8254a0d # v6.0.0

      - uses: astral-sh/setup-uv@11f9893b081a58869d3b5fccaea48c9e9e46f990 # v8.3.2

      - name: build
        run: uv run --only-group=doc zensical build --clean --strict

      - name: upload artifact
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5.0.0
        with:
          path: site

      - name: deploy
        id: deployment
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5.0.0
