# label PR's based on changed files
name: Pull Request Labeler
on:
  pull_request_target:
    types: [opened]

jobs:
  label_pull_request:
    permissions:
      contents: read
      pull-requests: write

    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v5.0.0
        if: github.repository == 'jorenham/optype'
