name: Pull Request Labeler
on:
  # needed for fork PRs; safe because no PR code is checked out
  pull_request_target: # zizmor: ignore[dangerous-triggers]
    types: [opened]

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  label_pull_request:
    name: label pull request
    permissions:
      contents: read
      pull-requests: write # apply labels

    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@bf12e9b00b37c5c0ca2b87b79b2daf7891dbda13 # v7.0.0
        if: github.repository == 'jorenham/optype'
