name: build and publish to PyPI

on:
  workflow_dispatch:
  push:
    tags: ["v*"]

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

env:
  UV_LOCKED: 1

jobs:
  pypi-publish:
    name: Publish release to PyPI
    runs-on: ubuntu-latest
    timeout-minutes: 5
    environment:
      name: pypi
      url: https://pypi.org/p/optype
    permissions:
      id-token: write # authenticate with PyPI via OIDC
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - uses: astral-sh/setup-uv@ae62891fec2bb8e7d6c99fc78c9fec3a63790f8d # v10.0.0
        with:
          python-version: "3.14"
          enable-cache: false

      - name: uv build
        run: uv build

      - name: publish to PyPI
        uses: pypa/gh-action-pypi-publish@dc37677b2e1c63e2034f94d8a5b11f265b73ba33 # v1.14.2
